# Generated by Django 2.0.7 on 2019-03-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comics',
            name='image',
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
    ]
